name: Sync to Hugging Face hub

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      - name: Setup Git LFS
        run: |
          git lfs install
          git lfs track "*.png"
          git add .gitattributes
          git commit -m "Configure LFS" || echo "No changes"

      - name: Push to Hugging Face Hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git remote add hf https://tsrivallabh:$HF_TOKEN@huggingface.co/spaces/tsrivallabh/Linkedin-AI-Assistant
          git push hf main --force
