name: 🚀 Sync to Hugging Face Space

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v4

      - name: 🤗 Sync with Hugging Face Hub
        uses: huggingface/hub-action@v1
        with:
          repo: tsrivallabh/Linkedin-AI-Assistant      # Your space
          repo-type: space
          space-sdk: docker
          private: false                               # boolean, no quotes!
          token: ${{ secrets.HF_TOKEN }}
